insert into semesters values ('Semester 1','A',1,32)
insert into semesters values ('Semester 2','B',1,32)
insert into semesters values ('Semester 3','C',1,33)
insert into semesters values ('Semester 4','D',1,32)
insert into semesters values ('Semester 5','E',1,32)
insert into semesters values ('Ministry Module','F',1,28)
insert into semesters values ('Miracle Living Module','G',1,32)
insert into semesters values ('Women of the World Volume 1','W',1,33)
insert into semesters values ('Women of the World Volume 2','W',1,32)