select * from persons

insert into persons values ('Rev. Bayless Conley',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. A.L. Gill',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. John Amstutz',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Lamar Boschman',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. John Bevere',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Dick Eastman',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Buddy Bell',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Christopher Gornold-Smith',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Terry Law',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Bill Winston',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Berin Gilfillan',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Stan DeKoven',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Larry Stockstill',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Reinhard Bonnke',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Jack Hayford',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. David Shibley',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Jim Feeney',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Ed Cole',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Jim Cobrae',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Joyce Meyer',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Brian Houston',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Billy Hornsby',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. A.R. Bernard',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Ray Comfort',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Dean Sherman',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Marilyn Hickey',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. T.L. Osborn',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Wayne Myers',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Dick Benjamin',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Willie George',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Jim Wideman',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Blaine Bartel',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. John Burns',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Gilbert Bilezikian',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Brick Cliff',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Keith Hazell & Rev. Jeremy Hazell',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. P.G. Vargis',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Bobbie Houston',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Lisa Bevere',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Deborah Cobrae',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Lisa Gilfillan',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Christine Caine',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Gloria Copeland',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Carolyn Klaus, MD',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Pat Harrison',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Cheryl Salem',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. John and Helen Burns',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Betty Price',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Janet Conley',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Darlene Zschech',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Judy Bauer',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Sue Bryan',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Shoddy Chase',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Dr. Berin & Rev. Lisa Gilfillan',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Danica Goward-Burns ',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Dawna Elguera',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Sonia Freeman',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Barbie Meyer',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Rev. Barbara Peters',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Blair Petrini',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Denise Renner',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Margaret Stunt',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Joyce Villalobos',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Holly Wagner',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Kerri Weems',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Gaby Wentland',NULL,NULL,NULL,NULL,NULL,6)
insert into persons values ('Lindsay Willis',NULL,NULL,NULL,NULL,NULL,6)

select * from persons
