begin tran

insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'The Authority of the Bible & The Doctrine of the Trinity','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'The Deity of Jesus','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'Salvation, Heaven & Hell, and Christ’s Return','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'The Person & Work of the Holy Spirit','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'Divine Healing','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Foundations of the Faith'),'Church Ordinances','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Holy Spirit','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Gifts of the Holy Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Vocal Gifts','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Revelation Gifts','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Power Gifts','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Gifts of Healing','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'Healing and the Great Commission','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'The Healing Power of God','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'Speaking Words of Healing','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Supernatural Living'),'Impartation Through Laying on of Hands','0.10')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Introduction to the New Testament','0.01')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Mathew, Mark, Luke: Three Portraits of Jesus Christ','0.02')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'John: A Fourth Portrait of Jesus Christ','0.03')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Acts: The Expansion of the Gospel','0.04')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Romans: The Gospel of Grace','0.05')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'1 & 2 Corinthians, Galatians: Living the Gospel of Grace','0.06')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Ephesians, Philippians, Colosians & Philemon: Letters from Prison','0.07')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'1 & 2 Thessalonians: The Lord''s Return; 1 & 2 Timothy, Titus: Leadership','0.08')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Hebrews-Jude: General Letters to Believers','0.09')
insert into sessions values ((select courseID from courses where coursename like 'New Testament Survey'),'Revelation: The Consummation of All Things','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Boschman'),'Priority, Purpose and Portrayal of Worship','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Boschman'),'The Role of Music in the Kingdom of God','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Boschman'),'The Signifcance of the New Song','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Boschman'),'Our Responsibility as Worshippers','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Boschman'),'How to Become a Worshipper','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Fear of the Lord'),'Fear of the Lord','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Power of Prayer'),'Its Threefold Potential','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Power of Prayer'),'What Prayer Is','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Power of Prayer'),'The Practice of Prayer PART 1','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Power of Prayer'),'The Practice of Prayer PART 2','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Power of Prayer'),'The Purpose of Prayer','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of Helps'),'The Journey of a Servant','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of Helps'),'God Uses Both Stars and Candles','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of Helps'),'Fear Not Leadership, Organization & Structure Part 1','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of Helps'),'Fear Not Leadership, Organization & Structure Part 2','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of Helps'),'Becoming a Servant of Fire','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Approaching the Old Testament','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'The Order of Books and Creation','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'The Image of God and the Fall','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Babel and Abraham, the Concepts of Covenant','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Abraham, Israel, Joseph, and Moses','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'The Tabernacle Worship','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Joshua, Judges and Ruth','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'The Kings, David, Psalms, and Hebrew Poetry','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Wisdom Literature, Division and Exile','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Old Testament Survey'),'Babylonian Captivity, Return from Exile, and the Prophets','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'The Divine Exchange PART 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'The Divine Exchange PART 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'The Triumph of Praise','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'What Activates Angels','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'How to Make Your Faith Work','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Essence of the Gospel'),'','')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'God’s Will and Healing','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'Healing in the Atonement','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'Full Salvation','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'Moses, the Serpent and Healing','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'The Mercy of Healing','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Jesus Our Healer Today'),'','')
insert into sessions values ((select courseID from courses where coursename like 'Living By Faith'),'Living By Faith PART 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Living By Faith'),'Living By Faith PART 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Introduction'),'Mobilize to Multiply','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Church-Based Training'),'Model of Ministry Training','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Church-Based Training'),'The Goal and Objective of Educational Ministry','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Church-Based Training'),'Planning Your Institute','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Cell Groups'),'Purposes of Cell Groups','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Cell Groups'),'Evangelizing the Lost','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Cell Groups'),'Raising Up Leaders','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Cell Groups'),'The Principles of Multiplication','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Cell Groups'),'Great Leaders in the Church','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Power Evangelism'),'Fire Brand Evangelists','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Power Evangelism'),'The Power of the Holy Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Power Evangelism'),'Integrity','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Power Evangelism'),'The Great Commission','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Power Evangelism'),'Fire of the Holy Spirit','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Leader''s Integrity'),'Integrity of Heart','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Leader''s Integrity'),'A Forgiving Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Vision'),'Embracing the Vision','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Vision'),'Qualities of a Visionary','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Vision'),'Focusing on the Vision','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Vision'),'God''s Vision and Your Vision','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Vision'),'Funding the Vision','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Church Planting'),'An Overview of Church Planting','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Church Planting'),'The Local Church as a Ministry Training Center','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Church Planting'),'Vocational Ministers in the Local Church','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Church Planting'),'Identifying Church-Planting Teams','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Church Planting'),'Preparing & Sending the Church-Planting Team','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Being Led By The Spirit'),'Spirit Directed & Spirit Power','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Being Led By The Spirit'),'How God Leads Us Through Our Spirits','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Being Led By The Spirit'),'Direction in Difficult Times','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Being Led By The Spirit'),'Priorities of Life','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Being Led By The Spirit'),'Pitfalls and Dangers When Seeking Guidance','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Promise Keeper'),'Promise Keeper','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Altar Call'),'How to Give an Altar Call','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Mindsets, Vision and Responsibility','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Responsibility and Trials','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Grumbling and Impatience','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Impatience and the Victim Mentality','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'The Victim Mentality and Self-pity','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Self-Worth','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Wilderness Mentalities'),'Comparison, Stubborness and Rebellion','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Developing Leaders'),'The Heart of a Leader','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Developing Leaders'),'Your Heart Determines the Course of Your Life','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Developing Leaders'),'Your Heart Determines Your Success in Life','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Developing Leaders'),'Leaders or Followers','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Developing Leaders'),'Pitfalls of Visionaries','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Cell Group Leaders'),'Effectiveness','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Reconcilliation'),'Introduction','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Reconcilliation'),'Origins and Destiny','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Reconcilliation'),'Fear: The Strategy of the Enemy','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Reconcilliation'),'Living a Reconciled Life','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Personal Evangelism'),'Hell''s Best Kept Secret','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Personal Evangelism'),'Atheism','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Personal Evangelism'),'Militant Evangelism','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Personal Evangelism'),'True and False Conversion','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Personal Evangelism'),'How to Get on Fire for God','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Spirtual Warfare'),'The Biblical Foundation','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Spirtual Warfare'),'Understanding Spiritual Warfare','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Spirtual Warfare'),'Warfare Prayer and the Gates of Hell','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Spirtual Warfare'),'Crashing the Gates of Hell','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Spirtual Warfare'),'Exercising Authority in Society','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Authority and Forgiveness'),'The Bait of Satan','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Authority and Forgiveness'),'Under Cover','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Spiritual Breakthrough'),'Bible Memorization - PART 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Spiritual Breakthrough'),'Bible Memorization - PART 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Spiritual Breakthrough'),'Breaking Generational Curses','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Jesus, Our Model','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Jesus, Our Inspiration','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Our Response','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Action','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Our Credibility','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Our Legality','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Christ Connection'),'Experience','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Living to Give'),'The Maximum Lifestyle','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Living to Give'),'How to Initiate a Lifestyle of Giving','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Living to Give'),'Exchanging Earthly Resources','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Living to Give'),'Living and Giving Beyond the Possible','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Living to Give'),'Can God? God Can!','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Biblical Eldership'),'What is a Biblical Elder?','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Biblical Eldership'),'The Function of Elders','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Biblical Eldership'),'Qualifications of Elders','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Biblical Eldership'),'The Fivefold Ministry PART 1','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Biblical Eldership'),'The Fivefold Ministry PART 2','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'What The Bible Says About Children''s Ministry','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'The Laws of Hospitality','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'The Last Days Harvest','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'Preaching to Children','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'Pastor-Driven Youth Ministry','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'How to Hold a Child''s Attention','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a New Generation'),'How to be an Excellent Storyteller','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Managing for Tomorrow'),'Using Puppets in Children''s Ministry','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Managing for Tomorrow'),'How to be a Problem Solver','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Managing for Tomorrow'),'Organizing Children''s Ministry for Growth','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Managing for Tomorrow'),'How to Get Others to Help You','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Ministering to Youth'),'Setting the Vision for Youth Ministry','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Ministering to Youth'),'Leading Leaders to Peak Performance','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Ministering to Youth'),'Effectively Communicating to Young People','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Ministering to Youth'),'Planning an Effective Youth Ministry','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Conquering the Sin Nature'),'Conquering the Sin Nature','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Heart of Ministry'),'Capturing the Heart of God','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Heart of Ministry'),'Cultivating an Excellent Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Renewed Like The Eagles'),'Live Like an Eagle','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Renewed Like The Eagles'),'What Makes an Eagle Majestic?','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Community & Gender'),'Community in Creation','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Community & Gender'),'God''s Intent through History','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Community & Gender'),'The Cross and Community','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Community & Gender'),'Relationships in Community','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Dynamic Preaching'),'The Need for Dynamic Preaching','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Dynamic Preaching'),'Character and Anointing','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Dynamic Preaching'),'Illustrations and Sermon Topics','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Dynamic Preaching'),'Organizing and Writing a Dynamic Sermon','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Dynamic Preaching'),'Altar Calls and Outlines','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Importance and Value of Prophetic Ministry','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Types of Prophetic Ministry','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'New Testament Prophets','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Releasing Prophetic Ministry in the Local Church','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Hearing the Voice of God','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Judging Prophetic Words','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Receiving and Responding to the Prophetic','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Prophetic Gatherings in the Local Church','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'False Revelation','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Foundations'),'Stepping Out','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Practical Points for Ministry'),'Vision and Setting Targets','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Practical Points for Ministry'),'Leading By Example','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Practical Points for Ministry'),'Leadership Principles for Growth','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Practical Points for Ministry'),'A Minister''s Marriage','0.04')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'Created in His Image','0.01')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'Our Image of the Father','0.02')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'New Creation Image','0.03')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'Exchanging Our Old Self Image','0.04')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'Our Image in Christ','0.05')
insert into sessions values ((select courseID from courses where coursename like 'New Creation Image'),'New Creation Benefits','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Know Your Enemy','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Authority on Earth','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Jesus, Our Example','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'The Church and Its Authority','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Satan''s Strategies Today','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Keys to the Kingdom','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'The Name of Jesus','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Authority of the Believer'),'Victorious Spiritual Warfare','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Gill'),'God''s Pattern for Praise and Worship','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Gill'),'Why, Who, When and Where','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Gill'),'God''s Eternal Purpose','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Gill'),'Expressions of Praise and Worship','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Praise and Worship - Gill'),'Victory Through Praise and Worship','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Prayer: Bringing Heaven to Earth'),'Lord, Teach Us to Pray','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Prayer: Bringing Heaven to Earth'),'Essentials of Successful Prayer','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Prayer: Bringing Heaven to Earth'),'Kingdom Advancing Prayers','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Prayer: Bringing Heaven to Earth'),'Prayer - The Voice of Faith','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Prayer: Bringing Heaven to Earth'),'Faith Filled Prayers','0.05')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'God''s View of Sickness and Disease','0.01')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'Jesus Is Our Healer','0.02')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'Jesus Is Our Example','0.03')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'The Holy Spirit and His Power','0.04')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'The Holy Spirit for All Believers','0.05')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'Ministering in Power','0.06')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'Ministering Through Action and Prayer','0.07')
insert into sessions values ((select courseID from courses where coursename like 'God''s Provision for Healing'),'Practical Help for Ministry','0.08')
insert into sessions values ((select courseID from courses where coursename like 'The Value of a Woman'),'Dream for Womanhood','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Value of a Woman'),'She is Gathering from the Four Corners of the Earth','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Value of a Woman'),'Let Kindness Rule','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Becoming a Mother/Mentor'),'Having the Heart of a Mother','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Becoming a Mother/Mentor'),'Sexual Purity','0.02')
insert into sessions values ((select courseID from courses where coursename like 'God''s Secret Weapon'),'God''s Design and Plan for Womanhood','0.01')
insert into sessions values ((select courseID from courses where coursename like 'God''s Secret Weapon'),'God''s Purposes for Women','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Disappointment'),'The One and the Many','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Disappointment'),'The God Who Sees','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Disappointment'),'Overcoming Discouragement and Depression','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Rising to Your Potential'),'Overcoming with God','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Rising to Your Potential'),'Your Thinking Defines You','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Divine Healing'),'The Truth and Traditions about Healing','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Divine Healing'),'Keys and Hindrances to Healing','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Divine Healing'),'The Believer’s Authority and the Results of Healing','0.03')
insert into sessions values ((select courseID from courses where coursename like 'AIDS Education'),'A General Overview of H.I.V. and A.I.D.S.','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of the Holy Spirit'),'Learning the Ways of the Holy Spirit','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of the Holy Spirit'),'How To Be Led by and Walk in the Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Ministry of the Holy Spirit'),'Knowing Who the Holy Spirit Is','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Grief'),'Grief','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Grief'),'Restoration','0.02')
insert into sessions values ((select courseID from courses where coursename like 'God''s Plan For Your Family'),'Covering Your Family','0.01')
insert into sessions values ((select courseID from courses where coursename like 'God''s Plan For Your Family'),'Rising Above Rejection','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Generational Blessings'),'The Miracles of Motherhood','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Generational Blessings'),'The Miracle in a Daddy''s Hug','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Being a Pastor''s Wife'),'Conquering Cancer & Being a Pastor''s Wife','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Church-Based Women''s Ministry'),'Ingredients for a Church-Based Women''s Ministry','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Difficulties in Leadership'),'Responsibility and Preparation','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Difficulties in Leadership'),'Keys to Victory','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Women in Worship'),'Live Life from a Position of Worship','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Women in Worship'),'Making Your Dreams a Reality','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Women in Worship'),'You Shall Go Out in Joy','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Women in Worship'),'Extravagant Female Worshippers','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Becoming a Minister'),'The Gospel Outline','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Becoming a Minister'),'Effectively Sharing Your Testimony','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Holy Spirit'),'How to Receive the Baptism of the Holy Spirit','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Holy Spirit'),'How to Minister the Baptism of the Holy Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Finding Your Calling'),'The Call of God','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Finding Your Calling'),'The Ministry of Reconciliation','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Esther Message'),'For Such A Time As This Pt. 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Esther Message'),'For Such A Time As This Pt. 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Anorexia & Bulimia '),'Overcoming Addictions','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Communicating With Teenagers'),'Communicating With Teenagers Part 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Communicating With Teenagers'),'Communicating With Teenagers Part 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Healing the Hurts of Abortion'),'Healing from Post-Abortion Trauma','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Healing the Hurts of Abortion'),'Overcoming Hate','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Making of a Miracle'),'Overcoming the Impossible','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Nine Principles of War'),'Overview of War','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Nine Principles of War'),'The First Six Principles of War','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Nine Principles of War'),'The Last Three Principles of War','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Mercy Ministries'),'Being the Difference','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Self-Esteem'),'Living Free From Shame','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Self-Esteem'),'Embracing God''s Freedom from Shame','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Sexual Abuse'),'Overcoming Sexual Abuse','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Sexual Abuse'),'Using the Gifts that God Gave Us','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Women of Wisdom'),'The Proverbs 31 Woman','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Female Friendships'),'The Value of Friendship','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Female Friendships'),'The Power of Friendship','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Female Friendships'),'How to Build Great Friendships','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Becoming Superwoman'),'Living Life Intentionally','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Becoming Superwoman'),'The Power of Salvation','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Miracles'),'God''s Miracles Today','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Miracles'),'Believing God for the Impossible','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Being Single and Happy'),'The Importance of Single Women in the Kingdom','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Being Single and Happy'),'Living Single and Fulfilled','0.02')


--commit tran

--rollback tran

select * from sessions