
select courseID from courses where coursename like 'Applying the Principles for Success'
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'The Spirit of Generosity','0.01')

begin tran
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'Tappling God''s Power for Reformation','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'Kingdom Success','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'Be a Blessing in the Workplace','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'Insights for Business Success','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Applying the Principles for Success'),'Conquering Culture Collisions','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Authority in the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Your Place of Authority','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Imparted Gifts','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'The Spirit of Intimidation (Part 1)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'The Spirit of Intimidation (Part 2)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Stir Up the Gift - Power','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Stir Up the Gift - Love','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Stir Up the Gift - Sound Mind','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Breaking Intimidation'),'Press On','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Breath of the Holies'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Breath of the Holies'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Breath of the Holies'),'Session 3','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Breath of the Holies'),'Session 4','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Changing Culture Through Marketplace Influence'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'Introduction to Christian & Islamic Theological Issues','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of the Trinity (Part 1)','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of the Trinity (Part 2)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of the Trinity (Part 3)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of the Trinity (Part 4)','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of the Trinity (Part 5)','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of Man (Part 1)','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'The Doctrine of Man (Part 2)','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'Islamic View of Jesus','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'Christian Response to the Islamic View of Jesus','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Christian & Islamic Theological Issues'),'Islam''s Challenge of the Scriptures','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Why Care About Muslims','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'How Muslims Come to Christ','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Biography of Muhammad (Part 1)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Biography of Muhammad (Part 2)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Muhammad''s Prophethood & Moral Character','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Historical Critique of the Sources for the Life of Muhammad','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Shariah Law and Society','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Qur''an Critique (Part 1)','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Qur''an Critique (Part 2)','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Qur''an Critique (Part 3)','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'Textual Criticism of the Qur''an','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),' ''Isa in Islam or Jesus in Christianity?','0.12')
insert into sessions values ((select courseID from courses where coursename like 'Christian Apologetics to Islam'),'A Guide to Finishing the Great Commission','0.13')
insert into sessions values ((select courseID from courses where coursename like 'Cleansing Stream'),'Walk in the Spirit','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Cleansing Stream'),'To Commit Everything to God','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Cleansing Stream'),'Speak Words of Life','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Cleansing Stream'),'Enter the Cleansing Stream','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Cleansing Stream'),'Press Toward the Goal','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Confronting Life''s Issues'),'Taming Your Tongue','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Confronting Life''s Issues'),'Supreme Confidence','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Confronting Life''s Issues'),'Confronting Without Offending','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Discipling the Nations Through Business'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Discovering Your Marketplace Assignment'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Discovering Your Marketplace Assignment'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Our Dominion Mandate (Part 1)','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Our Dominion Mandate (Part 2)','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Apostles Today (Part 1)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Apostles Today (Part 2)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Apostles Today (Part 3) & Apostolic Assignment (Part 1)','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Apostolic Assignment (Part 2)','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Doing the Works of Jesus (Part 1)','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Dominion, Wealth, & Social Transformation'),'Doing the Works of Jesus (Part 2)','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'The Eternal','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Eternal Home of the Dead','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Judgment of Deceived','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'The Great Falling Away','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'The Foundation','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Heaven','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'The Judgment Seat of Christ','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'God''s Custom House (Part 1)','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'God''s Custom House (Part 2)','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Multiplication (Part 1)','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Multiplication (Part 2)','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Driven By Eternity'),'Personal Influence','0.12')
insert into sessions values ((select courseID from courses where coursename like 'Economic, Social, and Enviromental Business'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Enmity Between the Two Seeds'),'The Good Seed','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Enmity Between the Two Seeds'),'Israel, the Seed of Abraham','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Enmity Between the Two Seeds'),'The Evil Seed','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Enmity Between the Two Seeds'),'Enmity Between the Two Seeds','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Ethics in the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'The Bible (Part 1)','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'The Bible (Part 2)','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'The Bible (Part 3)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'The Bible (Part 4)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Resurrection Factor (Part 1)','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Resurrection Factor (Part 2)','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Resurrection Factor (Part 3)','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Resurrection Factor (Part 4)','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Resurrection Factor (Part 5)','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Attributes of God (Part 1)','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Attributes of God (Part 2)','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Bible: Fact or Fiction (Part 1)','0.12')
insert into sessions values ((select courseID from courses where coursename like 'Evidence That Demands a Verdict'),'Bible: Fact or Fiction (Part 2)','0.13')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'God''s Pleased with Extraordinary','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'Revealed as We Are','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'You Can Do it!!','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'Newness of Life','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'Holiness','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'The Kingdom Within','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'The Access','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'Beyond Comprehension','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'True Faith is Relentless','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'What Are You Listening To?','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'The Flesh','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Extraordinary'),'God''s Imperial Rule','0.12')
insert into sessions values ((select courseID from courses where coursename like 'Faith in the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Getting Focused to See Results'),'Distraction Profile and Focus on Your Focus','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Getting Focused to See Results'),'Focus Lifestyle: Introduction','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Getting Focused to See Results'),'Focus Lifestyle: Identifying Distractions','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Getting Focused to See Results'),'Focus Lifestyle: Enviroment, Energy and Effort','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Getting Focused to See Results'),'Focus Lifestyle: Excellence and Execution','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Global Business, Am I My Brother''s Keeper?'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'How to Choose the Right Employees'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'How to Choose the Right Employees'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'How to Strategically Prepare for Any Negotiation'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'How to Strategically Prepare for Any Negotiation'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Intercession in the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Israel and the Church'),'Prophecy Being Fulfilled','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Israel and the Church'),'The Covenant Today','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Israel and the Church'),'Replacement Theology','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Kingdom Enterprise'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Kingdom Wealth'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Kingdom Wealth'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Principles'),'Church Growth in the Modern Age','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Leadership Principles'),'Building the Local Church through the Power and Presence of the Holy Spirit','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Conversion to Jesus and Being a Disciple: Personal Reflections','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Emergence of the Modern Secular Worldview','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Faith and Reason','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Evidence Against Scientific Naturalism and Evidence for God','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Postmodernism and Its Impact on Western Culture','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'The Search for God: How Does One Select a Religion in a Rational Way?','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Hell: Fact or Fiction?','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'Jesus Christ: The Only Way to God','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Loving God with All Your Mind'),'The Problem of Evil and Good','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Managing by Character'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Marketing and Keys to Success'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Marketing and Keys to Success'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Marketing to Government and Big Business'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Marketing to Government and Big Business'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Introduction to Muslim Evangelism','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Understanding Islam''s Beliefs and Practices','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Islam and Christianity Compared','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Muhammad - A Christian Critique','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'The Bible - A Christian Apologetic','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Confident Christianity','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Khilafah vs. Kingdom of God','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Which is the Religion of Peace, Islam or Christianity?','0.08')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Frequently Asked Questions (FAQ''s)','0.09')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'The Attraction of Islam','0.10')
insert into sessions values ((select courseID from courses where coursename like 'Muslim Evangelism'),'Missiological Methodologies Post-9/11','0.11')
insert into sessions values ((select courseID from courses where coursename like 'Navigating Betrayal'),'Recognizing Betrayal','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Navigating Betrayal'),'Overcoming the Hurt of Betrayal','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Ousting Babylon from the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Ousting Babylon from the Marketplace'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Ousting Babylon from the Marketplace'),'Session 3','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Ousting Babylon from the Marketplace'),'Session 4','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Overcoming Workplace Challenges in a Post-Christian Enviroment'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Practical Tips for Starting New Businesses'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Practical Tips for Starting New Businesses'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Preparing For The Future'),'Vision','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Preparing For The Future'),'Planning','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Preparing For The Future'),'Purpose','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Preparing For The Future'),'Possibilities','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Preparing For The Future'),'Peak Performance & Servanthood','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Discoveries Hidden in God''s Seven Appointed Feasts'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Discoveries Hidden in God''s Seven Appointed Feasts'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Discoveries Hidden in God''s Seven Appointed Feasts'),'Session 3','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Discoveries Hidden in God''s Seven Appointed Feasts'),'Session 4','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Mysteries of the Seven Feasts of Israel'),'The Seven Feasts of Israel','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Mysteries of the Seven Feasts of Israel'),'The Day of Atonement','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Mysteries of the Seven Feasts of Israel'),'The Fall and Spring Feasts','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Prophetic Mysteries of the Seven Feasts of Israel'),'The Prophetic Insight of the Fall Feasts','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Reaching a Tipping Point'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Receiving Your Inheritance'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Reforming the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Reforming the Marketplace'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Relating to Pastoral Covering'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Sexual Wholeness & Healing'),'Living Free from Sexual Immorality','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Sexual Wholeness & Healing'),'Overcoming Sexual Abuse','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Sexual Wholeness & Healing'),'Overcoming Sexual Addiction','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Sexual Wholeness & Healing'),'How to Have Great Married Sex','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Sexual Wholeness & Healing'),'Parenting Sexually Healthy Children','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Shepherding Business & Marketplace Leaders'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Shepherding Business & Marketplace Leaders - Marketplace Module Extras'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Ancient Jewish Wedding'),'The Rapture Revelation','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Ancient Jewish Wedding'),'The 14 Steps of the Ancient Jewish Wedding','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Ancient Jewish Wedding'),'The Secret Ascension','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Ancient Jewish Wedding'),'The Unfinished Meal','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'The Happy Life','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'It''s All About the Heart','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'What Test?','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'The Principle of the First','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'Breaking the Spirit of Mammon','0.05')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'Am I Generous?','0.06')
insert into sessions values ((select courseID from courses where coursename like 'The Blessed Life'),'The Principles of Multiplication','0.07')
insert into sessions values ((select courseID from courses where coursename like 'The Code of the Priest'),'The Order of Melchizedek','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Code of the Priest'),'The New Priesthood','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Code of the Priest'),'The High Priest','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Code of the Priest'),'Priest and King','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Surrendering Your Senses to the Holy Spirit','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Seeing: You Have More Than One Set of Eyes','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Hearing: Whatever He Hears, He Will Speak','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Feeling: From the Heart Flows the Issues of Life','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Tasting, Smelling & Other Leadings','0.05')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Knowing: The Sixth Sense','0.06')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Testing the Spirits: Don''t Believe Every Spirit!','0.07')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'The Spirit of Deception','0.08')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Exposing Demonic Influences','0.09')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Avoiding Common Pitfalls','0.10')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'The Safety Net: Cultivating Faith, Not Fear','0.11')
insert into sessions values ((select courseID from courses where coursename like 'The Discerner'),'Revelation''s Ultimate Purpose: When the Word Becomes Flesh','0.12')
insert into sessions values ((select courseID from courses where coursename like 'The Economics of Mutuality'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Five-Fold Effect in the Marketplace'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Journey to National Transformation'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Marriage Trinity'),'The Miracle of Marriage','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Marriage Trinity'),'The Difference Between a Secular and a Christian Marriage','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Marriage Trinity'),'The Greater Serves the Lesser','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Incarnation','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Selection','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Association','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Consecration','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Demonstration','0.05')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Delegation','0.06')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Supervision','0.07')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Reproduction','0.08')
insert into sessions values ((select courseID from courses where coursename like 'The Master Plan of Evangelism'),'Impartation','0.09')
insert into sessions values ((select courseID from courses where coursename like 'The Nehemiah People'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Nehemiah People'),'Session 2','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Power of the Tithe'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Seer and Prophet: Prophetic Streams','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Dimensions of the Prophetic Anointing','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Vision: The Power That Sustains','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'The Diversity of Visionary States','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Wisely Judging Revelatory Encounters','0.05')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Discerning of Spirits','0.06')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Dream Language','0.07')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Levels of Supernatural Visions','0.08')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'The Ecstatic Realms of the Spirit','0.09')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Standing in the Council of God','0.10')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'Hidden Streams of the Prophetic','0.11')
insert into sessions values ((select courseID from courses where coursename like 'The Seer'),'The Key of Intimacy to Open Heavens','0.12')
insert into sessions values ((select courseID from courses where coursename like 'The Seven Mountain Strategy'),'The Seven Mountain Strategy','0.01')
insert into sessions values ((select courseID from courses where coursename like 'The Seven Mountain Strategy'),'Spheres of Influence','0.02')
insert into sessions values ((select courseID from courses where coursename like 'The Seven Mountain Strategy'),'Journey to Convergence','0.03')
insert into sessions values ((select courseID from courses where coursename like 'The Seven Mountain Strategy'),'Hindrances to Convergence','0.04')
insert into sessions values ((select courseID from courses where coursename like 'The Seven Mountain Strategy'),'Worldview of Convergence','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Business Cycles & Kingdom Purposes'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Self and Others'),'The Five C''s of the Kingdom','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Self and Others'),'Personality (Part A)','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Self and Others'),'Personality (Part B)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Self and Others'),'Personality (Part C)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Understanding the Relational Side of Business'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Understanding Your Purpose'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Unlocking Hebrew Mysteries'),'Jewish Tradition and the Shofar','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Unlocking Hebrew Mysteries'),'Understanding Our Jewish Roots','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Unlocking Hebrew Mysteries'),'A Study on the Jewish Prayer Shawl','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Unlocking Hebrew Mysteries'),'The Tallit','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Vocational & Career Planning'),'Passion','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Vocational & Career Planning'),'Placement','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Vocational & Career Planning'),'Profession (Part A)','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Vocational & Career Planning'),'Profession (Part B)','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Warrior Craftsmen'),'Session 1','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'Focused Insights of Soft Skills: Introduction','0.01')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'Focused Insights Review of Communication & Collaboration','0.02')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'Focused Insights Review of Conflict Resolution & Confidence','0.03')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'Focused Insights Review of Creativity & Character','0.04')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'The Virtues of Honor and Excellence','0.05')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'The HEROES Principle (Part A)','0.06')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'The HEROES Principle (Part B): Examples','0.07')
insert into sessions values ((select courseID from courses where coursename like 'Workplace Preparation Skills'),'Interviewing for Success: Introduction & Advanced Steps','0.08')

rollback tran
commit tran

select * from sessions